services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - '80'
    environment:
      TZ: 'Asia/Dubai'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
    networks:
      - backend
    volumes:
      - pihole-data:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped

volumes:
  pihole-data:
  dnsmasq:

networks:
  backend:
    external: true