services:
  nginxpm:
    container_name: nginxpm
    image: jc21/nginx-proxy-manager:latest
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      - DB_POSTGRES_HOST=${DB_POSTGRES_HOST}
      - DB_POSTGRES_PORT=${DB_POSTGRES_PORT}
      - DB_POSTGRES_USER=${DB_POSTGRES_USER}
      - DB_POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - DB_POSTGRES_NAME=${DB_POSTGRES_NAME}
    networks:
      - frontend
      - backend
      - db
    volumes:
      - nginx-data:/data
      - nginx-certs:/etc/letsencrypt
    restart: unless-stopped

volumes:
  nginx-data:
  nginx-certs:

networks:
  frontend:
    external: true
  backend:
    external: true
  db:
    external: true