services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      HOMEPAGE_ALLOWED_HOSTS: dashboard.sabdullatif.xyz
      PUID: 1000 
      PGID: 1000 
    expose:
      - '3000'
    networks:
      - backend
    volumes:
      - ./config:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    restart: unless-stopped

networks:
  backend:
    external: true
