services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      HOMEPAGE_ALLOWED_HOSTS: dashboard.sabdullatif.xyz
      HOMEPAGE_VAR_PIHOLE_SECRET: ${HOMEPAGE_VAR_PIHOLE_SECRET}
      HOMEPAGE_VAR_PROMMOX_USERNAME: ${HOMEPAGE_VAR_PROMMOX_USERNAME}
      HOMEPAGE_VAR_PROMMOX_PASSWORD: ${HOMEPAGE_VAR_PROMMOX_PASSWORD}
      HOMEPAGE_VAR_PORTAINER_HOST: ${HOMEPAGE_VAR_PORTAINER_HOST}
      HOMEPAGE_VAR_PORTAINER_ENV: ${HOMEPAGE_VAR_PORTAINER_ENV}
      HOMEPAGE_VAR_PORTAINER_API_KEY: ${HOMEPAGE_VAR_PORTAINER_API_KEY}
      HOMEPAGE_VAR_NGINXPM_USERNMAE: ${HOMEPAGE_VAR_NGINXPM_USERNMAE}
      HOMEPAGE_VAR_NGINXPM_PASSWORD: ${HOMEPAGE_VAR_NGINXPM_PASSWORD}
    expose:
      - '3000'
    networks:
      - backend
    volumes:
      - ./config:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    restart: unless-stopped

networks:
  backend:
    external: true
