services:

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    restart: unless-stopped
    
    expose:
      - 3000
    
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"

    volumes:
      - grafana-data:/var/lib/grafana
    
    networks:
      - obs_net
      - infra_net

networks:
  obs_net:
    name: obs_net
    external: true
  infra_net:
    external: true
    name: infra_net

volumes:
  grafana-data: