services:
  telegraf:
    container_name: telegraf
    image: telegraf
    restart: unless-stopped
    environment:
      - TELEGRAF_DATABASE=${TELEGRAF_DATABASE}
      - TELEGRAF_USERNAME=${TELEGRAF_USERNAME}
      - TELEGRAF_PASSWORD=${TELEGRAF_PASSWORD}
      - TELEGRAF_POSTGRES_USERNAME=${TELEGRAF_POSTGRES_USERNAME}
      - TELEGRAF_POSTGRES_PASSWORD=${TELEGRAF_POSTGRES_PASSWORD}
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - backend
      - db
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    restart: unless-stopped
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_REPORTING_DISABLED=${INFLUXDB_REPORTING_DISABLED}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
      - INFLUXDB_HTTP_LOG_ENABLED=${INFLUXDB_HTTP_LOG_ENABLED}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    networks:
      - backend
    volumes:
      - influxdb_data:/var/lib/influxdb
  chronograf:
    container_name: chronograf
    image: chronograf
    restart: unless-stopped
    expose:
      - '8888'
    networks:
      - backend
    volumes:
      - chronograf_data:/var/lib/chronograf
    depends_on:
      - influxdb
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    expose:
      - '3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend
      - db

volumes:
  influxdb_data:
  chronograf_data:
  grafana_data:

networks:
  backend:
    external: true
  db:
    external: true