services:

  redis:
    container_name: shared_redis
    image: redis:7-alpine
    restart: unless-stopped

    ports:
      - "6379:6379"

    networks:
      - shared_net

    volumes:
      - redis-data:/data

    command: ["redis-server", "--appendonly", "yes"]

networks:
  shared_net:
    external: true
    name: shared_net

volumes:
  redis-data: