services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    
    expose:
      - 8080
    
    networks:
      - infra_net
    
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  infra_net:
    external: true

