services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    networks:
      - infra_net
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - 80
    environment:
      FTLCONF_dns_listeningMode: 'all'
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
    volumes:
      - /app/data/pihole/data:/etc/pihole
      - /app/data/pihole/dnsmasq:/etc/dnsmasq.d

networks:
  infra_net:
    name: infra_net
    external: true

