---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/


- greeting:
    text_size: xl
    text: Hi Samir!

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
        timeStyle: short

