services:

  nginxpm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxpm
    restart: unless-stopped
    environment:
      - DB_POSTGRES_HOST=postgres
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_USER=${NPM_DB_USER}
      - DB_POSTGRES_PASSWORD=${NPM_DB_PASSWORD}
      - DB_POSTGRES_NAME=${NPM_DB_NAME}

    networks:
      - infra_net
      - shared_net

    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    
    volumes:
      - /app/data/nginxpm/data:/data
      - /app/data/nginxpm/letsencrypt:/etc/letsencrypt

networks:
  infra_net:
    name: infra_net
    external: true
  shared_net:
    name: shared_net
    external: true

